### ISSUE TITLE
system power up from keyboard

### ISSUE THREAD

**Issue by voidstar78** [X16Community/x16-smc#13]
would there be a clean way to power up the X16 from the gamepad or keyboard?   as I recall, the original Apple2 had a power button up near the keyboard - but that was a very integrated case.     Not sure if possible across the PS/2 connector.

**Comment by mooinglemur** [comment]
This would be a question for @stefan-b-jakobsson  but after a quick look, it looks like the PS/2 ports are powered by VCC rather than 5VSB.  Hence the keyboard would be fully powered down if the system is in standby, and unable to trigger events.

**Comment by mooinglemur** [comment]
Gamepad, definitely not, because the controllers are clocked by the CPU through the 65C22.  The system needs to be running to do anything with those.

**Comment by stefan-b-jakobsson** [comment]
I don't have the official board or the schematics for it, so I can't contribute much. If the keyboard was powered at standby, we could easily tweak the SMC to wake the system.
