### ISSUE TITLE
SMC.BIN artefact creation

### ISSUE THREAD

**Issue by FlightControl-User** [X16Community/x16-smc#19]
Hi Stefan,

Would it be possible to create also as part of the deployment SMC.BIN files, in analogy with VERA.BIN and ROM.BIN?
It would be great to have a structure where the file name also would contain the version number, eg. SMC-R45.1.0.BIN.
The flasher tool uses this header to verify compatibility between SMC and ROMs.

So people can find this .BIN file also in the official artefact list of the [SMC CX16 community release page](https://github.com/X16Community/x16-smc/releases), so that I can direct to it from the [CX16 flasher update documentation](https://github.com/FlightControl-User/x16-flash/blob/main/README.md), so that people know where to find it ...

I have already a [method of creating such .BIN files](https://github.com/FlightControl-User/x16-flash/tree/main/bin).
The two python sources to be combined in one with a procedure, i'll work on that.

The cx16-smc-header-R45.1.0.hex contain 32 bytes, and contain version information for the SMC and the compatible ROMs:
 - The first three bytes is the SMC version number of the SMC.BIN.
 - The remaining bytes contain version information of the supported ROMs for the SMC.BIN, starting from the last byte backwards.

Sven

**Comment by stefan-b-jakobsson** [comment]
Hi,

As a first step, I've made a python script that makes the bin header. You can check it out here and test if it works:

https://github.com/stefan-b-jakobsson/x16-smc/tree/20231017-bin-artefact

It's in bin/build_bin.py

**Comment by FlightControl-User** [comment]
I have checked the python script and it looks great, and header.bin creation just from 16 bytes in a binary file is a good idea and simple :-).
Just keep in mind that:
- SMC R43.0.0 would be compatible with ROM 43, ROM R44 and ROM R45. Also note that R44 actually was a preview version (-44) and indeed R45 now also has (-45).
- SMC R45.1.0 would be compatible with ROM 45 ... 
- and next ROMs (ROM p46 (-46)) ...  You may want to add P46 (preview)  and R46 already?

Would suggest that we add these .BIN files to each SMC release as SMC-RVV.MM.NN.BIN, with the appropriate header.

**Comment by FlightControl-User** [comment]
The python script just now seems to have disappeared.

**Comment by FlightControl-User** [comment]
I want to build the same yml for the deployment of the flasher tool. It will help the community and i won't be a bottle neck :-).

**Comment by stefan-b-jakobsson** [comment]
Pull request is now ready for review

**Comment by mooinglemur** [comment]
Closed by #20
