### ISSUE TITLE
Action build currently not working

### ISSUE THREAD

**Issue by stefan-b-jakobsson** [X16Community/x16-smc#26]
The Action build is currently failing due to a certificate for azduino.com that expired today.

I mailed the web master, which seems to be Spence Konde himself. His answer below:

= = = = =

Ugh. No ETA on fix because that server is trashed and the webserver is not belived to be restartable. We're in ther middle of a server migration that I thought was going to be done before the cert ran out. Until that migration is complete [azduino.com](http://azduino.com/) will not be able to service https requests. I apologize for any inconvenience.

This is a critical priority issue for us, however, there are 3 even more critical priority issues that must be resolved even more urgently. 

= = = = =

Hi,

I just want to let you know that the certificate of [azduino.com](http://azduino.com/) has expired.

The server is accessed in a Github action to fetch and install the ATtiny platform.

Cheers,

Stefan.

**Comment by stefan-b-jakobsson** [comment]
I replaced all references to https://azduino.com with http://azduino.com in the file package_drazzy.com_index.json in pull request #25.

That made the build work again. Don't know how stable though, until Spence got their problems sorted.

**Comment by mooinglemur** [comment]
Workaround merged in #25 to use http addresses.  Keeping this issue open as a reminder to revert once the certs are updated.

**Comment by stefan-b-jakobsson** [comment]
Fixed by PR #30
